### PR TITLE
cloned and copied david's proxy

### PR DESCRIPTION
**Pull request by ikaur1718**
I cloned the legacy code from FEC staybnb of david's proxy. 
commented some code to check if my service was working.
I am ready to get it reviewed as everything looks like it is working.

### CODE REVIEW

**Comment by ikaur1718** [comment]
@grantdiamond Please review the proxy

**Comment by grantdiamond** [comment]
Our legacy proxy looks good to me. I will be using the same code, but may have to add some endpoints in the future to accommodate write-functionality for my database.

**Comment by ikaur1718** [comment]
Yes Grant, I was also very confused by that but for my proxy I would like to change the endpoint, so we should discuss them before hand.

Thanks

**Comment by grantdiamond** [comment]
I agree. Please bring this up at standup tomorrow and we will discuss it with Riley.

**Pull request merged**
